var webpack=require ('webpack');
var path =require('path');
module.exports={
    devtool:'incline-source-map',

    entry:{
        'index':'./src/index.js'
    },
    output:{
        //path ko resolve ani join
        path:path.resolve(__dirname,'dist'),
        filename:'main.js'
    },
    //loader
    module:{
        rules:[
            {
            test:/\.js$/,//Starts with duita slash
            exclude:/node_modules/,
            use:'babel-loader'
        }
        ]
},
devServer:{
    //those content that are not generated by webpack
    contentBase:path.join(__dirname,"public/"),
    port:3939,
    hot:true,//HMR resloading

    //to serve webpack files
    publicPath:"http://localhost:3939/dist/"
}
}

